name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint-prettier-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Corepack enable
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Run eslint
        run: yarn run eslint

      - name: Run prettier
        run: yarn run prettier

      - name: Run unit tests
        run: yarn run test
